// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"ACTPO_AutoBalance","status":false,"description":"v3.6 Автоматическая балансировка характеристик врагов по уровню партии [ACTPO]","parameters":{"EnableAutoBalance":"true","BalanceFormula":"3.00","Multiplier":"0.1","HPCoefficient":"1.0","ATKCoefficient":"0.8","BossHPCoefficient":"1.0","BossATKCoefficient":"1.0","MiniBossHPCoefficient":"1.0","MiniBossATKCoefficient":"1.0","BossMultiplier":"1.5","BossNote":"<boss>","MiniBossNote":"<miniboss>","MiniBossMultiplier":"1.2","ScaleHP":"true","ScaleMP":"true","ScaleATK":"true","ScaleDEF":"true","ScaleMAT":"true","ScaleMDF":"true","ScaleAGI":"true","ScaleLUK":"true","ScaleEXP":"true","ScaleGold":"true","MinLevel":"1","MaxLevel":"99","MinMultiplier":"0.5","MaxMultiplier":"5.0","DifficultyScaling":"true","DebugMode":"false"}},
{"name":"ACTPO_EnemyAnimations","status":true,"description":"v1.0.0 - ACTPO Система анимации врагов (SV спрайты + эффекты) [ACTPO]","parameters":{"Debug":"false","No Movement":"false","Enemies Celebrate":"true","SV Enemies Collapse":"true"}},
{"name":"ACTPO_EnemyHP","status":true,"description":"v1.1.0 Отображение здоровья врагов (Universal) [ACTPO]","parameters":{"Показывать HP Бары":"true","Показывать HP Текст":"true","Ширина HP Бара":"100","Высота HP Бара":"8","Смещение Y от спрайта":"-50","Текст Y смещение":"-65","Размер шрифта":"14","Цвет фона HP Бара":"#000000","Цвет заполнения HP Бара":"#ff0000","Цвет текста HP":"#ffffff","Включить анимации":"true","Задержка скрытия (секунды)":"0","Показывать только при уроне":"false"}},
{"name":"ACTPO_Minimap","status":false,"description":"v1.0 Миникарта [ACTPO UI]","parameters":{"Map X":"Graphics.boxWidth - 400","Map Y":"10","Map Width":"150","Map Height":"150","Scale":"4","Opacity":"200","Wall Color":"#666666","Floor Color":"#cccccc","Player Color":"#ff0000"}},
{"name":"ACTPO_QuestConfig","status":true,"description":"","parameters":{}},
{"name":"ACTPO_KillTracker","status":true,"description":"v1.0 Simple Kill Tracker [ACTPO]","parameters":{}},
{"name":"ACTPO_SimpleHUD","status":true,"description":"v1.0 Ultra-Simple Quest HUD [ACTPO]","parameters":{"HUD X":"Graphics.boxWidth - 450","HUD Y":"10","HUD Width":"400","Font Size":"16"}},
{"name":"ACTPO_SafeKeypad","status":true,"description":"[v1.0] Визуальный ввод кода для сейфов (специально для Bitz)","parameters":{}},
{"name":"TelegramWebApp","status":true,"description":"Telegram Web App Integration & Fixes","parameters":{}},
{"name":"LockPuzzleMV","status":true,"description":"v4.0 Touch-first lockpicking. One-finger control, no Enter required.","parameters":{}},
{"name":"BF_RatCatch","status":true,"description":"BitzFantasy — Мини-игра ловли крыс v2. Картинка RatRun.png, без знака $.","parameters":{}},
{"name":"BF_Nitrogen","status":true,"description":"BitzFantasy — Мини-игра жидкого азота. RPG Maker MV.","parameters":{}},
{"name":"BF_Cheater","status":true,"description":"BitzFantasy — мини-игра разоблачения жулика.","parameters":{}},
{"name":"SafeCodeUI","status":true,"description":"[BitzFantasy] Красивый сенсорный кодовый замок сейфа. RPG Maker MV.","parameters":{}},
{"name":"BF_BrunoInterrogation","status":true,"description":"BitzFantasy — мини-приложение «Допрос Бруно» v1.0","parameters":{}}
];
