// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"TelegramWebApp","status":true,"description":"Telegram Web App Integration & Fixes","parameters":{}},
{"name":"BF_DetectiveMode","status":true,"description":"Bitz Fantasy — детективный режим: отключает боевые столкновения.","parameters":{}},
{"name":"BF_QuestConfig","status":true,"description":"Bitz Fantasy — единый редактируемый конфиг всех квестов","parameters":{}},
{"name":"BF_QuestSystem","status":true,"description":"Bitz Fantasy — единый движок квестов, шагов, журнала и мини-приложений","parameters":{}},
{"name":"BF_QuestMap","status":true,"description":"Bitz Fantasy — красивая карта-пергамент: местность, игрок, текущая цель и маршрут","parameters":{}},
{"name":"BF_Inventory","status":true,"description":"Bitz Fantasy — Inventory / Bag UI. Adds a separate inventory button beside the journal and gear menu.","parameters":{}},
{"name":"BF_GearMenu","status":true,"description":"Bitz Fantasy - Полная замена стандартного меню на меню-шестерёнку.","parameters":{}},
{"name":"BF_RatCatch","status":true,"description":"Bitz Fantasy - Rat Catch v8. Fixed MV Bitmap error, clearer broom controls and reliable quest completion.","parameters":{}},
{"name":"BF_Nitrogen","status":true,"description":"BitzFantasy — Nitrogen V6. Реальная мини-игра с ручным вентилем, инерцией, риском и таймингами.","parameters":{}},
{"name":"BF_SwitchPuzzle","status":true,"description":"Bitz Fantasy — «Электрощит Вермилиона». Мини-игра с 5 тумблерами.","parameters":{}},
{"name":"BF_Cheater","status":true,"description":"BitzFantasy — мини-игра разоблачения жулика. Понятный интерфейс 816x624.","parameters":{}},
{"name":"LockPuzzleMV","status":true,"description":"v4.0 Touch-first lockpicking. One-finger control, no Enter required.","parameters":{}},
{"name":"SafeCodeUI","status":true,"description":"[BitzFantasy] Красивый сенсорный кодовый замок сейфа. RPG Maker MV.","parameters":{}},
{"name":"BF_KeySearchPuzzle","status":true,"description":"Bitz Fantasy — мини-игра поиска потерянных ключей у водосточной решётки","parameters":{}},
{"name":"BF_UnderwaterTunnel","status":true,"description":"Bitz Fantasy — затопленный туннель: аркадная мини-игра в стиле Flappy Bird","parameters":{}},
{"name":"BF_Minecart","status":true,"description":"Bitz Fantasy — Мини-игра «Вагонетки» для перехода через пещеры.","parameters":{}},
{"name":"BF_PanelPuzzle1","status":true,"description":"Bitz Fantasy — Пульт 1: электрическая разводка","parameters":{}},
{"name":"BF_PanelPuzzle2","status":true,"description":"Bitz Fantasy — Пульт 2: синхронизация шестерён","parameters":{}},
{"name":"BF_PanelPuzzle3","status":true,"description":"Bitz Fantasy — Пульт 3: код запуска","parameters":{}},
{"name":"BF_LaserSecurity","status":true,"description":"Вращающиеся лазеры для стелс-участка Bitz Fantasy.","parameters":{"Return Map ID":"29","Return X":"19","Return Y":"19","Fade Delay":"30","Default Length":"7","Default Speed":"60","Default Width":"5","Hit Radius":"0.22","Color":"16724787"}},
{"name":"BF_CameraSecurity","status":true,"description":"Bitz Fantasy — камеры и охрана для стелс-участков","parameters":{"Return Map":"29","Return X":"20","Return Y":"34","Alert SE":"Buzzer1"}}
];
