/*:
 * @plugindesc BitzFantasy — Допрос Бруно v3.0 Full
 * @help Plugin Command: BRUNO_INTERROGATION
 * Управление: мышь/touch, стрелки, Enter/Space.
 * Успех: переменная 20 = 1.
 */
(function(){'use strict';
var WAIT='bruno_interrogation', RESULT=20;
var oldPC=Game_Interpreter.prototype.pluginCommand;
Game_Interpreter.prototype.pluginCommand=function(c,a){oldPC.call(this,c,a);if(String(c).toUpperCase()==='BRUNO_INTERROGATION'){this.setWaitMode(WAIT);SceneManager.push(Scene_BrunoInterrogation);}};
var oldUW=Game_Interpreter.prototype.updateWaitMode;
Game_Interpreter.prototype.updateWaitMode=function(){if(this._waitMode===WAIT)return SceneManager._scene instanceof Scene_BrunoInterrogation;return oldUW.call(this);};
function Scene_BrunoInterrogation(){this.initialize.apply(this,arguments)}
Scene_BrunoInterrogation.prototype=Object.create(Scene_MenuBase.prototype);Scene_BrunoInterrogation.prototype.constructor=Scene_BrunoInterrogation;
Scene_BrunoInterrogation.prototype.initialize=function(){Scene_MenuBase.prototype.initialize.call(this);this.round=0;this.score=0;this.pressure=0;this.timer=0;this.done=false;this.failed=false;this.msg='';this.streak=0;this.started=Graphics.frameCount;};
Scene_BrunoInterrogation.prototype.create=function(){Scene_MenuBase.prototype.create.call(this);this.win=new Window_BrunoFull(0,0,Graphics.boxWidth,Graphics.boxHeight,this);this.addWindow(this.win);this.win.activate();this.win.select(0);};
Scene_BrunoInterrogation.prototype.data=function(){
var d=[
[['СЕРВЕРЫ — МАЙНИНГ','Мощности казино использовались для добычи криптовалюты',true,28],['АЗОТ — ОХЛАЖДЕНИЕ','Азот применялся только для охлаждения оборудования',false,0],['ОБЫЧНЫЕ СЕРВЕРЫ','Они хранили только игровые данные',false,-8]],
[['ШУЛЕР — УСТРОЙСТВО','У игрока было устройство для скрытого обмана',true,30],['ВЕЗЕНИЕ','Он просто невероятно хорошо играл',false,-10],['СЛУЧАЙНОСТЬ','Выигрыши никак между собой не связаны',false,-8]],
[['БУХГАЛТЕРИЯ — СВЯЗЬ','Майнинг, шулеры и деньги проходят через одну схему',true,35],['ТОЛЬКО ЗАРПЛАТЫ','Все подозрительные суммы — обычные расходы',false,-10],['ТОЛЬКО ШУЛЕР','Доход зависел только от одного игрока',false,-12]]
];return d[this.round];};
Scene_BrunoInterrogation.prototype.heading=function(){return ['УЛИКА №1 — СЕРВЕРЫ','УЛИКА №2 — ШУЛЕР','УЛИКА №3 — БУХГАЛТЕРИЯ'][this.round]||'ДЕЛО РАСКРЫТО';};
Scene_BrunoInterrogation.prototype.bruno=function(){return ['«Серверы? Обычное оборудование казино. Вы ничего не докажете.»','«Шулер? Ему просто везло. При чём здесь я?»','«Деньги могли поступать откуда угодно. Бухгалтерия ничего не доказывает.»'][this.round]||'«Ладно... достаточно. Вы всё поняли.»';};
Scene_BrunoInterrogation.prototype.answer=function(i){if(this.timer>0||this.done)return;var d=this.data()[i];if(!d)return;if(d[2]){this.score+=d[3]+Math.max(0,30-Math.floor((Graphics.frameCount-this.started)/60));this.pressure=Math.min(100,this.pressure+34);this.streak++;this.msg=this.round===0&&$gameVariables.value(12)===1?'«Азот охлаждал оборудование. А серверы использовали мощности казино для майнинга.»':['«Это связывает улику с делом напрямую.»','«Устройство доказывает, что выигрыши были организованы.»','«Цифры сошлись: все три части — одна схема.»'][this.round];SoundManager.playOk();this.round++;if(this.round>=3){this.done=true;this.score+=this.streak*25;this.timer=90;}else this.timer=65;}else{this.pressure=Math.max(0,this.pressure+d[3]);this.streak=0;this.msg='Бруно: «И что это должно доказывать?» Слабая улика. Давление падает.';this.timer=55;SoundManager.playBuzzer();}this.win.refresh();};
Scene_BrunoInterrogation.prototype.update=function(){Scene_MenuBase.prototype.update.call(this);if(this.timer>0){this.timer--;if(this.timer===0){if(this.done){$gameVariables.setValue(RESULT,1);this.popScene();}else{this.msg='';this.win.refresh();}}}};
function Window_BrunoFull(x,y,w,h,s){this.scene=s;this._cards=[];Window_Selectable.prototype.initialize.call(this,x,y,w,h);this.opacity=0;this.refresh();}
Window_BrunoFull.prototype=Object.create(Window_Selectable.prototype);Window_BrunoFull.prototype.constructor=Window_BrunoFull;Window_BrunoFull.prototype.maxItems=function(){return 3;};
Window_BrunoFull.prototype.box=function(c,x,y,w,h,fill,line){c.fillRect(x,y,w,h,fill);if(line){c.fillRect(x,y,w,2,line);c.fillRect(x,y+h-2,w,2,line);c.fillRect(x,y,2,h,line);c.fillRect(x+w-2,y,2,h,line);}};
Window_BrunoFull.prototype.wrap=function(t,x,y,w,lh,max){var c=this.contents,ws=String(t).split(/\s+/),lines=[],line='';for(var i=0;i<ws.length;i++){var z=line?line+' '+ws[i]:ws[i];if(c.measureTextWidth(z)>w&&line){lines.push(line);line=ws[i];}else line=z;}if(line)lines.push(line);if(max&&lines.length>max)lines=lines.slice(0,max);for(i=0;i<lines.length;i++)this.drawText(lines[i],x,y+i*lh,w,'left');return lines.length*lh;};
Window_BrunoFull.prototype.hit=function(x,y){for(var i=0;i<this._cards.length;i++){var r=this._cards[i];if(x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h)return i;}return -1;};
Window_BrunoFull.prototype.refresh=function(){var c=this.contents,W=this.contentsWidth(),s=this.scene;c.clear();this._cards=[];c.fontSize=28;c.textColor='#f0c84b';this.drawText('ДОПРОС БРУНО',0,4,W,'center');c.fontSize=14;c.textColor='#aeb5c0';this.drawText(s.heading(),0,39,W,'center');for(var p=0;p<3;p++)c.fillRect(W/2-138+p*92,64,72,6,p<s.round?'#67cf63':'#3a414b');c.fontSize=14;c.textColor='#dce2e8';this.drawText('ДАВЛЕНИЕ',35,80,110,'left');c.fillRect(35,101,260,12,'#252b33');c.fillRect(35,101,260*s.pressure/100,12,s.pressure>70?'#d95b4f':'#d7ad45');c.fontSize=13;c.textColor='#9ca6b1';this.drawText('Очки: '+Math.max(0,s.score),35,120,260,'center');var dx=325,top=88,d=s.data();this.box(c,25,155,275,145,'#171d25','#806237');c.fontSize=42;c.textColor='#c99559';this.drawText('Б',25,178,275,'center');c.fontSize=20;c.textColor='#fff';this.drawText('БРУНО',25,235,275,'center');c.fontSize=13;c.textColor='#8d98a5';this.drawText('ПОДОЗРЕВАЕМЫЙ',25,263,275,'center');this.box(c,dx,top,W-dx-20,88,'#11161d','#46515e');c.fontSize=17;c.textColor='#f1f3f5';this.wrap(s.bruno(),dx+14,top+12,W-dx-48,22,3);if(!s.done){c.fontSize=18;c.textColor='#f0c84b';this.drawText('ВЫБЕРИ САМОЕ СИЛЬНОЕ ДОКАЗАТЕЛЬСТВО',dx,190,W-dx-20,'left');for(var n=0;n<3;n++){var yy=220+n*76,sel=n===this.index();this._cards.push({x:dx,y:yy,w:W-dx-20,h:64});this.box(c,dx,yy,W-dx-20,64,sel?'#352c19':'#1a2028',sel?'#e0b746':'#46505b');c.fontSize=16;c.textColor=sel?'#fff0ad':'#f3f4f5';this.drawText(d[n][0],dx+12,yy+6,W-dx-44,'left');c.fontSize=12;c.textColor='#aeb6c0';this.wrap(d[n][1],dx+12,yy+29,W-dx-44,15,2);}c.fontSize=12;c.textColor='#7e8995';this.drawText('↑↓ выбор • Enter подтверждение • клик/касание',dx,458,W-dx-20,'center');if(s.msg){this.box(c,dx,482,W-dx-20,75,'#20251d','#8c7136');c.fontSize=14;c.textColor='#f1dfaa';this.wrap(s.msg,dx+10,493,W-dx-40,18,3);}}else{this.box(c,dx,210,W-dx-20,180,'#18251a','#4f9c4a');c.fontSize=29;c.textColor='#7be35e';this.drawText('ДЕЛО РАСКРЫТО',dx,235,W-dx-20,'center');c.fontSize=18;c.textColor='#d7e9d2';this.wrap('Бруно сломлен. Три улики складываются в одну схему.',dx+25,285,W-dx-70,24,3);c.fontSize=22;c.textColor='#f0c84b';this.drawText('Результат: '+s.score+' очков',dx,350,W-dx-20,'center');}};
Window_BrunoFull.prototype.update=function(){Window_Selectable.prototype.update.call(this);if(this.scene.done)return;var ch=false;if(Input.isTriggered('down')){this.select((this.index()+1)%3);ch=true;}if(Input.isTriggered('up')){this.select((this.index()+2)%3);ch=true;}if(ch){SoundManager.playCursor();this.refresh();}if(Input.isTriggered('ok'))this.scene.answer(this.index());if(TouchInput.isTriggered()){var i=this.hit(TouchInput.x,TouchInput.y);if(i>=0){this.select(i);this.scene.answer(i);}}};
window.Scene_BrunoInterrogation=Scene_BrunoInterrogation;
})();
