/*:
 * @plugindesc BitzFantasy — Разоблачение жулика v3.0 Full
 * @help Plugin Command: Cheater start
 * Мышь/touch. Успех включает Self Switch A события.
 */
(function(){'use strict';var CM={mapId:0,eventId:0};var old=Game_Interpreter.prototype.pluginCommand;Game_Interpreter.prototype.pluginCommand=function(c,a){old.call(this,c,a);if(String(c).toLowerCase()==='cheater'&&a&&String(a[0]).toLowerCase()==='start'){CM.mapId=$gameMap.mapId();CM.eventId=this._eventId;SceneManager.push(Scene_CheaterMini);}};
function outline(b,x,y,w,h,c,t){t=t||2;b.fillRect(x,y,w,t,c);b.fillRect(x,y+h-t,w,t,c);b.fillRect(x,y,t,h,c);b.fillRect(x+w-t,y,t,h,c);}
function Scene_CheaterMini(){this.initialize.apply(this,arguments)}Scene_CheaterMini.prototype=Object.create(Scene_Base.prototype);Scene_CheaterMini.prototype.constructor=Scene_CheaterMini;
Scene_CheaterMini.prototype.initialize=function(){Scene_Base.prototype.initialize.call(this);this.round=0;this.target=-1;this.locked=false;this.phase=0;this.hits=0;this.misses=0;this.score=0;this.flash=0;this.pos=[170,408,646];this.swapCount=0;};
Scene_CheaterMini.prototype.create=function(){Scene_Base.prototype.create.call(this);var b=new Sprite(ImageManager.loadPicture('CheaterMini/cheater_background'));b.scale.x=Graphics.boxWidth/816;b.scale.y=Graphics.boxHeight/624;this.addChild(b);this.ui=new Sprite(new Bitmap(Graphics.boxWidth,160));this.addChild(this.ui);this.status=new Sprite(new Bitmap(Graphics.boxWidth,60));this.status.y=555;this.addChild(this.status);this.m=[];for(var i=0;i<3;i++){var z=new Sprite(new Bitmap(190,70));z.x=this.pos[i]-95;z.y=360;z._i=i;this.addChild(z);this.m.push(z);}this.ch=new Sprite(ImageManager.loadSystem('CheaterMini/cheater'));this.ch.anchor.x=.5;this.ch.anchor.y=1;this.ch.x=this.pos[0];this.ch.y=350;this.addChild(this.ch);this.refresh();this.setStatus('Наблюдай. Запомни, где остановился жулик.');this.move();};
Scene_CheaterMini.prototype.refresh=function(){var b=this.ui.bitmap;b.clear();b.fillRect(0,0,Graphics.boxWidth,160,'rgba(4,5,10,.92)');b.fontSize=30;b.textColor='#f0d16a';b.drawText('РАЗОБЛАЧЕНИЕ ЖУЛИКА',0,10,Graphics.boxWidth,40,'center');b.fontSize=17;b.textColor='#fff';b.drawText('Раунд '+(this.round+1)+'/5     Точность: '+(this.hits)+'/'+Math.max(1,this.hits+this.misses),10,55,Graphics.boxWidth-20,28,'center');for(var i=0;i<3;i++){var c=this.m[i].bitmap;c.clear();c.fillRect(3,3,184,64,'rgba(8,17,25,.94)');outline(c,3,3,184,64,i===this.target&&!this.locked?'#e0b746':'#5b8795',2);c.fontSize=22;c.textColor='#e8f5ff';c.drawText('СЛОТ №'+(i+1),0,19,190,30,'center');}};
Scene_CheaterMini.prototype.setStatus=function(t){var b=this.status.bitmap;b.clear();b.fillRect(65,0,Graphics.boxWidth-130,55,'rgba(5,10,18,.94)');outline(b,65,0,Graphics.boxWidth-130,55,'#7db4c8',2);b.fontSize=20;b.textColor='#fff';b.drawText(t,75,13,Graphics.boxWidth-150,30,'center');};
Scene_CheaterMini.prototype.move=function(){var self=this;this.locked=true;var oldI=this.target<0?0:this.target,n=Math.floor(Math.random()*3);while(n===oldI)n=Math.floor(Math.random()*3);this.target=n;var steps=4+this.round;var t=0,from=this.ch.x,to=this.pos[n];var id=setInterval(function(){t+=.045;var p=Math.min(1,t);self.ch.x=from+(to-from)*p;self.ch.y=350-Math.sin(p*Math.PI)*22;if(p>=1){clearInterval(id);self.ch.y=350;var swaps=steps;var count=0;var sid=setInterval(function(){var a=Math.floor(Math.random()*3),bb=Math.floor(Math.random()*3);if(a===bb)bb=(bb+1)%3;var tmp=self.pos[a];self.pos[a]=self.pos[bb];self.pos[bb]=tmp;self.m[a].x=self.pos[a]-95;self.m[bb].x=self.pos[bb]-95;count++;self.swapCount++;if(count>=swaps){clearInterval(sid);self.locked=false;self.setStatus('Он остановился! Где он?');self.refresh();}},100);}},30);};
Scene_CheaterMini.prototype.update=function(){Scene_Base.prototype.update.call(this);if(this.flash>0)this.flash--;if(this.locked||!TouchInput.isTriggered())return;var x=TouchInput.x,y=TouchInput.y;if(this.phase===0){for(var i=0;i<3;i++){var m=this.m[i];if(x>=m.x&&x<=m.x+190&&y>=m.y&&y<=m.y+70){this.pick(i);return;}}}else{var dx=x-this.ch.x,dy=y-(this.ch.y-95);if(Math.abs(dx)<90&&Math.abs(dy)<125)this.success();else this.setStatus('Ничего. Ищи спрятанное устройство.');}};
Scene_CheaterMini.prototype.pick=function(i){if(i!==this.target){this.misses++;this.round=0;this.score=Math.max(0,this.score-100);this.setStatus('Промах! Жулик понял, что ты следишь. Сначала!');SoundManager.playBuzzer();this.move();return;}this.hits++;this.round++;this.score+=150+this.round*50;SoundManager.playOk();if(this.round>=5){this.phase=1;this.locked=false;this.ch.scale.x=1.35;this.ch.scale.y=1.35;this.ch.x=Graphics.boxWidth/2;this.ch.y=500;for(var k=0;k<3;k++)this.m[k].opacity=45;this.setStatus('Теперь обыщи его. Нажми точно на устройство на ноге.');}else{this.setStatus('Верно! Он двигается быстрее. Раунд '+this.round+'/5.');this.move();}};
Scene_CheaterMini.prototype.success=function(){this.locked=true;this.score+=500;if(CM.mapId===$gameMap.mapId()&&CM.eventId>0)$gameSelfSwitches.setValue([$gameMap.mapId(),CM.eventId,'A'],true);var z=new Sprite(ImageManager.loadSystem('CheaterMini/success'));z.anchor.x=.5;z.anchor.y=.5;z.x=Graphics.boxWidth/2;z.y=210;this.addChild(z);this.setStatus('Устройство найдено! Жулик разоблачён.');var t=new Sprite(new Bitmap(Graphics.boxWidth,100));t.y=270;t.bitmap.fontSize=28;t.bitmap.textColor='#9cff9c';t.bitmap.drawText('ДОКАЗАТЕЛЬСТВО НАЙДЕНО!',0,10,Graphics.boxWidth,40,'center');t.bitmap.fontSize=20;t.bitmap.textColor='#f0d16a';t.bitmap.drawText('Очки: '+this.score,0,52,Graphics.boxWidth,30,'center');this.addChild(t);setTimeout(function(){SceneManager.pop();},1500);};window.Scene_CheaterMini=Scene_CheaterMini;})();
