/*:
 * @plugindesc BitzFantasy — Мини-игра жидкого азота v3.0 Full
 * @help Plugin Command: Nitrogen start
 * Переменная 12 +1, Self Switch A после успеха. Мышь/touch.
 */
(function(){'use strict';var N={mapId:0,eventId:0};var old=Game_Interpreter.prototype.pluginCommand;Game_Interpreter.prototype.pluginCommand=function(c,a){old.call(this,c,a);if(String(c).toLowerCase()==='nitrogen'&&a&&String(a[0]).toLowerCase()==='start'){N.mapId=$gameMap.mapId();N.eventId=this._eventId;SceneManager.push(Scene_NitrogenMini);}};
function outline(b,x,y,w,h,c,t){t=t||2;b.fillRect(x,y,w,t,c);b.fillRect(x,y+h-t,w,t,c);b.fillRect(x,y,t,h,c);b.fillRect(x+w-t,y,t,h,c);}
function Scene_NitrogenMini(){this.initialize.apply(this,arguments)}Scene_NitrogenMini.prototype=Object.create(Scene_Base.prototype);Scene_NitrogenMini.prototype.constructor=Scene_NitrogenMini;
Scene_NitrogenMini.prototype.initialize=function(){Scene_Base.prototype.initialize.call(this);this._round=1;this._progress=0;this._mistake=0;this._timer=0;this._locked=false;this._sequence=[];this._pressure=50;this._stage=0;};
Scene_NitrogenMini.prototype.create=function(){Scene_Base.prototype.create.call(this);this.createBackground();this.createTitle();this.createTank();this.createControls();this.createStatus();this.startRound();};
Scene_NitrogenMini.prototype.createBackground=function(){var s=new Sprite(ImageManager.loadPicture('NitrogenMini/nitrogen_background'));s.scale.x=Graphics.boxWidth/816;s.scale.y=Graphics.boxHeight/624;this.addChild(s);};
Scene_NitrogenMini.prototype.createTitle=function(){var b=new Bitmap(Graphics.boxWidth,70);b.fillRect(0,0,Graphics.boxWidth,70,'rgba(0,0,0,.74)');b.fontSize=30;b.textColor='#d9f4ff';b.drawText('ДОБЫЧА ЖИДКОГО АЗОТА',0,8,Graphics.boxWidth,36,'center');b.fontSize=17;b.textColor='#fff';b.drawText('Не перепутай порядок и удерживай давление в зелёной зоне',0,43,Graphics.boxWidth,25,'center');this.addChild(new Sprite(b));};
Scene_NitrogenMini.prototype.createTank=function(){this._tank=new Sprite(ImageManager.loadSystem('NitrogenMini/nitro_tank'));this._tank.x=250;this._tank.y=205;this._tank.scale.x=1.15;this._tank.scale.y=1.15;this.addChild(this._tank);this._steam=new Sprite(ImageManager.loadSystem('NitrogenMini/steam'));this._steam.x=280;this._steam.y=120;this._steam.opacity=150;this.addChild(this._steam);};
Scene_NitrogenMini.prototype.createControls=function(){this._buttons=[];var names=['ВЕНТИЛЬ','ДАВЛЕНИЕ','ЗАБОР АЗОТА'],files=['valve','gauge','canister'],xs=[90,330,570];for(var i=0;i<3;i++){var spr=new Sprite(ImageManager.loadSystem('NitrogenMini/'+files[i]));spr.anchor.x=.5;spr.anchor.y=.5;spr.x=xs[i];spr.y=385;spr.scale.x=.72;spr.scale.y=.72;spr._idx=i;this.addChild(spr);var p=new Sprite(new Bitmap(200,58));p.x=xs[i]-100;p.y=445;p._idx=i;p.bitmap.fillRect(3,3,194,52,'rgba(4,18,35,.92)');outline(p.bitmap,3,3,194,52,'#59bfff',2);p.bitmap.fontSize=20;p.bitmap.textColor='#fff';p.bitmap.drawText(names[i],0,14,200,28,'center');this.addChild(p);this._buttons.push(spr);this._buttons.push(p);}};
Scene_NitrogenMini.prototype.createStatus=function(){this._status=new Sprite(new Bitmap(Graphics.boxWidth,120));this._status.y=500;this.addChild(this._status);this._hint=new Sprite(new Bitmap(Graphics.boxWidth,50));this._hint.y=120;this.addChild(this._hint);};
Scene_NitrogenMini.prototype.startRound=function(){var a=[0,1,2];for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t;}this._sequence=a;this._progress=0;this._mistake=0;this._timer=0;this._pressure=50;this._stage=0;this.updateStatus(this.actionText());};
Scene_NitrogenMini.prototype.actionText=function(){var idx=this._sequence[this._progress];return 'Раунд '+this._round+'/3 • '+(this._progress+1)+'/3: '+(idx===0?'открой вентиль':idx===1?'стабилизируй давление':'забери азот');};
Scene_NitrogenMini.prototype.updateStatus=function(text){var b=this._status.bitmap;b.clear();b.fillRect(55,0,Graphics.boxWidth-110,106,'rgba(3,13,25,.9)');outline(b,55,0,Graphics.boxWidth-110,106,'#4db9ff',2);b.fontSize=22;b.textColor='#e8f7ff';b.drawText(text,65,10,Graphics.boxWidth-130,32,'center');b.fontSize=16;b.textColor='#f4d36b';b.drawText('Ошибки: '+this._mistake+'     Давление: '+Math.round(this._pressure)+'%',65,48,Graphics.boxWidth-130,25,'center');b.fillRect(210,80,396,10,'#25313b');b.fillRect(210+396*Math.max(0,Math.min(100,this._pressure-25))/50,80,4,10,'#d95b4f');b.fillRect(210,80,396*.8,10,'rgba(90,210,120,.25)');};
Scene_NitrogenMini.prototype.update=function(){Scene_Base.prototype.update.call(this);if(this._locked)return;this._timer++;this._pressure+=Math.sin(Graphics.frameCount/14)*.22+(this._progress===1?Math.sin(Graphics.frameCount/5)*.12:0);if(this._progress===1&&Math.random()<.035)this._pressure+=Math.random()<.5?-2:2;this._pressure=Math.max(0,Math.min(100,this._pressure));this._steam.opacity=125+Math.sin(Graphics.frameCount/10)*35;this._steam.x=280+Math.sin(Graphics.frameCount/20)*5;if(this._progress===1&&this._pressure<25||this._progress===1&&this._pressure>75){if(Graphics.frameCount%30===0)this.showHint('Внимание: давление уходит из безопасной зоны!');}if(this._timer>2400)this.failRound();this.updateStatus(this.actionText());this.updateTouch();};
Scene_NitrogenMini.prototype.updateTouch=function(){if(!TouchInput.isTriggered())return;var idx=this.hitButton(TouchInput.x,TouchInput.y);if(idx<0)return;var need=this._sequence[this._progress];if(idx===need){if(idx===1&&this._pressure>25&&this._pressure<75){this._pressure=50;}else if(idx===1){this._mistake++;this.showHint('Давление было слишком нестабильным!');this.shakeTank();SoundManager.playBuzzer();return;}this._progress++;this.pulseButton(idx);SoundManager.playOk();if(this._progress>=3){if(this._round>=3)this.successRound();else{this._round++;this.showHint('Раунд пройден! Оборудование разогревается...');this.startRound();}}else this.updateStatus(this.actionText());}else{this._mistake++;this._pressure=Math.max(0,this._pressure-8);this.showHint('Ошибка! Последовательность нарушена.');this.shakeTank();SoundManager.playBuzzer();}};
Scene_NitrogenMini.prototype.hitButton=function(x,y){for(var i=0;i<3;i++){var b=this._buttons[i*2];if(b){var dx=x-b.x,dy=y-b.y;if(dx*dx+dy*dy<=80*80)return i;}var p=this._buttons[i*2+1];if(p&&x>=p.x&&x<=p.x+200&&y>=p.y&&y<=p.y+58)return i;}return -1;};
Scene_NitrogenMini.prototype.pulseButton=function(i){var b=this._buttons[i*2];b.scale.x=.86;b.scale.y=.86;var self=this;setTimeout(function(){if(b){b.scale.x=.72;b.scale.y=.72;}},120);};
Scene_NitrogenMini.prototype.shakeTank=function(){var tank=this._tank,base=250,n=0,id=setInterval(function(){if(!tank){clearInterval(id);return;}tank.x=base+(n%2?8:-8);n++;if(n>7){tank.x=base;clearInterval(id);}},30);};
Scene_NitrogenMini.prototype.showHint=function(t){this._hint.bitmap.clear();this._hint.bitmap.fontSize=21;this._hint.bitmap.textColor='#fff';this._hint.bitmap.drawText(t,0,0,Graphics.boxWidth,42,'center');};
Scene_NitrogenMini.prototype.failRound=function(){this.showHint('Давление сорвалось! Система сброшена — попробуй снова.');this.startRound();};
Scene_NitrogenMini.prototype.successRound=function(){this._locked=true;var v=Number($gameVariables.value(12)||0)+1;$gameVariables.setValue(12,v);if(N.mapId===$gameMap.mapId()&&N.eventId>0)$gameSelfSwitches.setValue([$gameMap.mapId(),N.eventId,'A'],true);var b=this._status.bitmap;b.clear();b.fillRect(55,0,Graphics.boxWidth-110,106,'rgba(10,50,20,.95)');outline(b,55,0,Graphics.boxWidth-110,106,'#70e27c',2);b.fontSize=28;b.textColor='#9cff9c';b.drawText('АЗОТ УСПЕШНО ИЗВЛЕЧЁН!',65,12,Graphics.boxWidth-130,40,'center');b.fontSize=17;b.textColor='#fff';b.drawText('Система выдержала все три этапа.',65,55,Graphics.boxWidth-130,28,'center');setTimeout(function(){SceneManager.pop();},1300);};window.Scene_NitrogenMini=Scene_NitrogenMini;})();
