/*:
 * @plugindesc BitzFantasy — Крысоловка v5.0 Full Quest Mini-game
 * @help Plugin Command: RatCatch start
 * Цель: поймать всех крыс в подвале. Мышь/touch + стрелки/WASD.
 * Успех: переменная 11 +1 и Self Switch A события.
 */
(function(){'use strict';var GAME_TIME=55*60,R={mapId:0,eventId:0};var old=Game_Interpreter.prototype.pluginCommand;Game_Interpreter.prototype.pluginCommand=function(c,a){old.call(this,c,a);if(String(c).toUpperCase()==='RATCATCH'&&a&&String(a[0]).toLowerCase()==='start'){R.mapId=$gameMap.mapId();R.eventId=this._eventId;SceneManager.push(RatCatchScene);}};
function RatCatchScene(){this.initialize.apply(this,arguments)}RatCatchScene.prototype=Object.create(Scene_Base.prototype);RatCatchScene.prototype.constructor=RatCatchScene;
RatCatchScene.prototype.initialize=function(){Scene_Base.prototype.initialize.call(this);this._time=GAME_TIME;this._ended=false;this._won=false;this._hits=0;this._caught=0;this._combo=0;this._lastHit=-99;this._spawned=false;this._rats=[];this._trap={x:680,y:330,w:72,h:62};this._walls=[{x:250,y:115,w:150,h:28},{x:510,y:115,w:28,h:140},{x:205,y:290,w:180,h:28},{x:450,y:325,w:145,h:28}];};
RatCatchScene.prototype.create=function(){Scene_Base.prototype.create.call(this);this.createBackground();this.createArena();this.createRats();this.createHud();this.createInput();this._msg('Подвал кишит крысами. Загоняй их в ловушку!');};
RatCatchScene.prototype.createBackground=function(){this._bg=new Sprite(new Bitmap(Graphics.boxWidth,Graphics.boxHeight));var b=this._bg.bitmap;b.fillAll('#211a16');b.fillRect(28,65,Graphics.boxWidth-56,Graphics.boxHeight-100,'#5b4638');b.fillRect(38,75,Graphics.boxWidth-76,Graphics.boxHeight-120,'#342821');this.addChild(this._bg);};
RatCatchScene.prototype.createArena=function(){this._arena=new Sprite(new Bitmap(760,410));this._arena.x=40;this._arena.y=80;var b=this._arena.bitmap;b.fillRect(0,0,760,410,'#6a503d');b.fillRect(8,8,744,394,'#30251f');for(var x=15;x<740;x+=40)b.fillRect(x,18,2,374,'#46372e');for(var y=20;y<390;y+=40)b.fillRect(12,y,736,2,'#46372e');for(var i=0;i<this._walls.length;i++){var w=this._walls[i];b.fillRect(w.x,w.y,w.w,w.h,'#4c392f');b.fillRect(w.x+4,w.y+4,w.w-8,w.h-8,'#6d5140');}var t=this._trap;b.fillRect(t.x,t.y,t.w,t.h,'#17110e');b.fillRect(t.x+5,t.y+5,t.w-10,t.h-10,'#a47745');b.fillRect(t.x+12,t.y+12,t.w-24,t.h-24,'#090807');b.font='bold 17px Arial';b.textColor='#fff0bd';b.drawText('ЛОВУШКА',t.x-5,t.y+23,t.w+10,'center');this.addChild(this._arena);};
RatCatchScene.prototype.createRats=function(){var starts=[[110,100],[620,90],[150,240],[430,210],[610,300],[350,350]];for(var i=0;i<starts.length;i++){var bmp=ImageManager.loadCharacter('RatRun'),s=new Sprite(bmp);s.anchor.x=.5;s.anchor.y=.5;s.setFrame(0,0,48,48);this.addChild(s);this._rats.push({x:starts[i][0],y:starts[i][1],vx:(Math.random()-.5)*2.4,vy:(Math.random()-.5)*2.4,r:18,sprite:s,caught:false,panic:0});}};
RatCatchScene.prototype.createHud=function(){this._hud=new Sprite(new Bitmap(Graphics.boxWidth,70));var b=this._hud.bitmap;b.fillRect(0,0,Graphics.boxWidth,70,'rgba(8,5,4,.88)');b.font='bold 25px Arial';b.textColor='#f0d39b';b.drawText('КРЫСЫ В ПОДВАЛЕ',35,8,330,'left');this.addChild(this._hud);this._stats=new Sprite(new Bitmap(430,50));this._stats.x=370;this._stats.y=8;this.addChild(this._stats);this._msgSprite=new Sprite(new Bitmap(760,50));this._msgSprite.x=40;this._msgSprite.y=500;this.addChild(this._msgSprite);};
RatCatchScene.prototype.createInput=function(){this._zones=[];for(var i=0;i<4;i++){var z=new Sprite(new Bitmap(110,70));z.opacity=0;z._dir=i;this.addChild(z);this._zones.push(z);}};
RatCatchScene.prototype._msg=function(t){var b=this._msgSprite.bitmap;b.clear();b.font='bold 19px Arial';b.textColor='#f4e1bb';b.drawText(t,0,8,760,'center');};
RatCatchScene.prototype.update=function(){Scene_Base.prototype.update.call(this);if(this._ended){if(Input.isTriggered('ok')||TouchInput.isTriggered())SceneManager.pop();return;}this._time--;if(this._time<=0){this.finish(false,'Крысы разбежались по подвалу!');return;}this.updateRats();this.updateControls();this.updateHud();if(this._caught>=this._rats.length)this.finish(true,'ХЛОП! Все крысы пойманы!');};
RatCatchScene.prototype.updateRats=function(){for(var i=0;i<this._rats.length;i++){var r=this._rats[i];if(r.caught)continue;r.panic=Math.max(0,r.panic-1);if(Math.random()<.012){var a=Math.random()*Math.PI*2;r.vx+=Math.cos(a)*(r.panic?0.55:.25);r.vy+=Math.sin(a)*(r.panic?0.55:.25);}var sp=Math.sqrt(r.vx*r.vx+r.vy*r.vy),max=r.panic?4.8:3.0;if(sp>max){r.vx*=max/sp;r.vy*=max/sp;}var nx=r.x+r.vx,ny=r.y+r.vy;if(nx<25||nx>735){r.vx*=-1;nx=Math.max(25,Math.min(735,nx));}if(ny<25||ny>385){r.vy*=-1;ny=Math.max(25,Math.min(385,ny));}for(var j=0;j<this._walls.length;j++){var w=this._walls[j];if(this.circleRect(nx,ny,r.r,w)){if(!this.circleRect(r.x,ny,r.r,w))r.vy*=-1;else if(!this.circleRect(nx,r.y,r.r,w))r.vx*=-1;else{r.vx*=-1;r.vy*=-1;}nx=r.x+r.vx;ny=r.y+r.vy;}}r.x=nx;r.y=ny;r.sprite.x=40+r.x;r.sprite.y=80+r.y;r.sprite.setFrame((Math.floor(Graphics.frameCount/7)%3)*48,0,48,48);if(this.inTrap(r)){r.caught=true;r.sprite.opacity=0;this._caught++;this._combo++;this._msg('ХЛОП! '+this._caught+'/'+this._rats.length+' • серия x'+this._combo);SoundManager.playOk();}}};
RatCatchScene.prototype.inTrap=function(r){var t=this._trap;return r.x>t.x+10&&r.x<t.x+t.w-10&&r.y>t.y+10&&r.y<t.y+t.h-10;};
RatCatchScene.prototype.updateControls=function(){var dir=null;if(Input.isTriggered('left')||Input.isTriggered('a'))dir=0;if(Input.isTriggered('right')||Input.isTriggered('d'))dir=1;if(Input.isTriggered('up')||Input.isTriggered('w'))dir=2;if(Input.isTriggered('down')||Input.isTriggered('s'))dir=3;if(TouchInput.isTriggered()){var x=TouchInput.x-40,y=TouchInput.y-80,nearest=-1,bd=99999;for(var i=0;i<this._rats.length;i++){if(this._rats[i].caught)continue;var dx=x-this._rats[i].x,dy=y-this._rats[i].y,d=dx*dx+dy*dy;if(d<bd){bd=d;nearest=i;}}if(nearest>=0){var r=this._rats[nearest],dx=x-r.x,dy=y-r.y;if(Math.abs(dx)+Math.abs(dy)<150)dir=Math.abs(dx)>Math.abs(dy)?(dx<0?0:1):(dy<0?2:3);else if(x<150)dir=0;else if(x>610)dir=1;else if(y<100)dir=2;else if(y>330)dir=3;}}if(dir!==null&&Graphics.frameCount-this._lastHit>10)this.broomHit(dir);};
RatCatchScene.prototype.broomHit=function(dir){this._lastHit=Graphics.frameCount;var ax=0,ay=0;if(dir===0)ax=1;if(dir===1)ax=-1;if(dir===2)ay=1;if(dir===3)ay=-1;var best=null,bd=140;for(var i=0;i<this._rats.length;i++){var r=this._rats[i];if(r.caught)continue;var d=Math.sqrt((r.x-(this._trap.x+this._trap.w/2))*(r.x-(this._trap.x+this._trap.w/2))+(r.y-(this._trap.y+this._trap.h/2))*(r.y-(this._trap.y+this._trap.h/2)));var hit=Math.sqrt((r.x-(this._ratCenterX()))*(r.x-(this._ratCenterX()))+(r.y-(this._ratCenterY()))*(r.y-(this._ratCenterY())));if(hit<bd){bd=hit;best=r;}}if(best){best.vx+=ax*2.6;best.vy+=ay*2.6;best.panic=35;this._hits++;SoundManager.playCursor();this._msg('ВЗМАХ! Загоняй её к ловушке.');}else{this._combo=0;this._msg('Мимо! Подойди ближе к крысе.');}};
RatCatchScene.prototype._ratCenterX=function(){var best=null,bd=99999;for(var i=0;i<this._rats.length;i++){var r=this._rats[i];if(r.caught)continue;var d=(r.x-380)*(r.x-380)+(r.y-205)*(r.y-205);if(d<bd){bd=d;best=r;}}return best?best.x:380;};RatCatchScene.prototype._ratCenterY=function(){var best=null,bd=99999;for(var i=0;i<this._rats.length;i++){var r=this._rats[i];if(r.caught)continue;var d=(r.x-380)*(r.x-380)+(r.y-205)*(r.y-205);if(d<bd){bd=d;best=r;}}return best?best.y:205;};
RatCatchScene.prototype.updateHud=function(){var b=this._stats.bitmap;b.clear();b.font='bold 18px Arial';b.textColor='#f4e1bb';b.drawText('Поймано: '+this._caught+'/'+this._rats.length+'    Взмахов: '+this._hits,0,0,430,'right');b.font='16px Arial';b.textColor='#d6b878';b.drawText('Время: '+Math.ceil(this._time/60)+' сек.',0,25,430,'right');};
RatCatchScene.prototype.circleRect=function(cx,cy,r,rect){var px=Math.max(rect.x,Math.min(cx,rect.x+rect.w)),py=Math.max(rect.y,Math.min(cy,rect.y+rect.h)),dx=cx-px,dy=cy-py;return dx*dx+dy*dy<r*r;};
RatCatchScene.prototype.finish=function(win,msg){if(this._ended)return;this._ended=true;this._won=win;this._msg(msg);var ov=new Sprite(new Bitmap(620,170));ov.x=98;ov.y=205;ov.bitmap.fillRect(0,0,620,170,'rgba(25,18,14,.96)');ov.bitmap.font='bold 34px Arial';ov.bitmap.textColor=win?'#9cff9c':'#ff9b8f';ov.bitmap.drawText(win?'ПОДВАЛ ОЧИЩЕН!':'КРЫСЫ РАЗБЕЖАЛИСЬ',0,22,620,45,'center');ov.bitmap.fontSize=19;ov.bitmap.textColor='#f4e1bb';ov.bitmap.drawText('Поймано: '+this._caught+'/'+this._rats.length+'    Взмахов: '+this._hits,0,80,620,30,'center');ov.bitmap.drawText('Нажмите Enter или коснитесь экрана',0,120,620,28,'center');this.addChild(ov);if(win){$gameVariables.setValue(11,Number($gameVariables.value(11)||0)+1);if(R.mapId===$gameMap.mapId()&&R.eventId>0)$gameSelfSwitches.setValue([$gameMap.mapId(),R.eventId,'A'],true);}};window.RatCatchScene=RatCatchScene;})();
