/*:
 * @plugindesc BitzFantasy — Крысоловка v6.0 Quest Mini-game
 * @help Plugin Command: RatCatch start
 * Цель: очистить подвал от 6 крыс. Клик по крысе выбирает её,
 * затем нажимай большую кнопку-стрелку с нужной стороны, чтобы махнуть веником.
 * Стрелки/WASD тоже работают. После успеха: Variable 11 +1, Self Switch A.
 */
(function(){
'use strict';
var GAME_TIME=75*60, R={mapId:0,eventId:0};
var old=Game_Interpreter.prototype.pluginCommand;
Game_Interpreter.prototype.pluginCommand=function(c,a){old.call(this,c,a);if(String(c).toUpperCase()==='RATCATCH'&&a&&String(a[0]).toLowerCase()==='start'){R.mapId=$gameMap.mapId();R.eventId=this._eventId;SceneManager.push(RatCatchScene);}};
function RatCatchScene(){this.initialize.apply(this,arguments)}
RatCatchScene.prototype=Object.create(Scene_Base.prototype);RatCatchScene.prototype.constructor=RatCatchScene;
RatCatchScene.prototype.initialize=function(){Scene_Base.prototype.initialize.call(this);this._time=GAME_TIME;this._ended=false;this._hits=0;this._caught=0;this._selected=-1;this._swing=0;this._swingDir=-1;this._rats=[];this._trap={x:665,y:320,w:85,h:70};this._walls=[{x:245,y:110,w:160,h:28},{x:500,y:105,w:30,h:150},{x:190,y:285,w:185,h:28},{x:440,y:325,w:155,h:28}];};
RatCatchScene.prototype.create=function(){Scene_Base.prototype.create.call(this);this.createBackground();this.createArena();this.createRats();this.createHud();this.createControls();this._msg('Сначала КЛИКНИ ПО КРЫСЕ. Затем выбери стрелку, куда её толкнуть.');};
RatCatchScene.prototype.createBackground=function(){this._bg=new Sprite(new Bitmap(Graphics.boxWidth,Graphics.boxHeight));var b=this._bg.bitmap;b.fillAll('#191412');b.fillRect(25,62,Graphics.boxWidth-50,Graphics.boxHeight-92,'#4c382d');b.fillRect(36,73,Graphics.boxWidth-72,Graphics.boxHeight-113,'#2b211d');this.addChild(this._bg);};
RatCatchScene.prototype.createArena=function(){this._arena=new Sprite(new Bitmap(760,410));this._arena.x=40;this._arena.y=80;var b=this._arena.bitmap;b.fillRect(0,0,760,410,'#654b3a');b.fillRect(8,8,744,394,'#30251f');for(var x=15;x<740;x+=40)b.fillRect(x,18,2,374,'#46362c');for(var y=20;y<390;y+=40)b.fillRect(12,y,736,2,'#46362c');for(var i=0;i<this._walls.length;i++){var w=this._walls[i];b.fillRect(w.x,w.y,w.w,w.h,'#47352c');b.fillRect(w.x+4,w.y+4,w.w-8,w.h-8,'#735441');}var t=this._trap;b.fillRect(t.x,t.y,t.w,t.h,'#110d0b');b.fillRect(t.x+5,t.y+5,t.w-10,t.h-10,'#b07b40');b.fillRect(t.x+12,t.y+12,t.w-24,t.h-24,'#080706');b.font='bold 17px Arial';b.textColor='#fff1bd';b.drawText('ЛОВУШКА',t.x-8,t.y+24,t.w+16,'center');this.addChild(this._arena);};
RatCatchScene.prototype.createRats=function(){var starts=[[100,90],[610,90],[120,235],[430,205],[610,285],[330,350]];for(var i=0;i<starts.length;i++){var bmp=ImageManager.loadCharacter('RatRun'),s=new Sprite(bmp);s.anchor.x=.5;s.anchor.y=.5;s.setFrame(0,0,48,48);this.addChild(s);this._rats.push({x:starts[i][0],y:starts[i][1],vx:(Math.random()-.5)*2.0,vy:(Math.random()-.5)*2.0,r:17,sprite:s,caught:false,panic:0,frame:i%3});}};
RatCatchScene.prototype.createHud=function(){this._hud=new Sprite(new Bitmap(Graphics.boxWidth,72));var b=this._hud.bitmap;b.fillRect(0,0,Graphics.boxWidth,72,'rgba(7,5,4,.94)');b.font='bold 25px Arial';b.textColor='#f0d39b';b.drawText('ОХОТА НА КРЫС',28,7,300,'left');this.addChild(this._hud);this._stats=new Sprite(new Bitmap(500,55));this._stats.x=300;this._stats.y=8;this.addChild(this._stats);this._msgSprite=new Sprite(new Bitmap(760,48));this._msgSprite.x=40;this._msgSprite.y=505;this.addChild(this._msgSprite);};
RatCatchScene.prototype.createControls=function(){this._buttons=[];var defs=[['←','ТОЛКНУТЬ ВЛЕВО',90,425,0],['→','ТОЛКНУТЬ ВПРАВО',250,425,1],['↑','ТОЛКНУТЬ ВВЕРХ',490,425,2],['↓','ТОЛКНУТЬ ВНИЗ',650,425,3]];for(var i=0;i<defs.length;i++){var d=defs[i],s=new Sprite(new Bitmap(145,62));s.x=d[2]-72;s.y=d[3]-31;s._dir=d[4];this.drawButton(s.bitmap,d[0],d[1],false);this.addChild(s);this._buttons.push(s);}};
RatCatchScene.prototype.drawButton=function(b,arrow,label,active){b.clear();b.fillRect(2,2,141,58,active?'rgba(180,120,45,.98)':'rgba(15,11,9,.96)');b.fillRect(2,2,141,3,active?'#ffe28a':'#8c6747');b.font='bold 28px Arial';b.textColor=active?'#fff6cf':'#f0d39b';b.drawText(arrow,4,11,42,34,'center');b.font='bold 12px Arial';b.drawText(label,42,17,95,28,'center');};
RatCatchScene.prototype._msg=function(t){var b=this._msgSprite.bitmap;b.clear();b.font='bold 18px Arial';b.textColor='#f4e1bb';b.drawText(t,0,8,760,'center');};
RatCatchScene.prototype.update=function(){Scene_Base.prototype.update.call(this);if(this._ended){if(Input.isTriggered('ok')||TouchInput.isTriggered())SceneManager.pop();return;}this._time--;if(this._time<=0){this.finish(false,'Время вышло! Крысы разбежались.');return;}this.updateRats();this.updateSelection();this.updateControls();this.updateSwing();this.updateHud();if(this._caught>=this._rats.length)this.finish(true,'Отлично! Подвал очищен от крыс.');};
RatCatchScene.prototype.updateRats=function(){for(var i=0;i<this._rats.length;i++){var r=this._rats[i];if(r.caught)continue;r.panic=Math.max(0,r.panic-1);if(Math.random()<(r.panic?0.025:0.010)){var a=Math.random()*Math.PI*2;r.vx+=Math.cos(a)*(r.panic?.5:.2);r.vy+=Math.sin(a)*(r.panic?.5:.2);}var sp=Math.sqrt(r.vx*r.vx+r.vy*r.vy),max=r.panic?4.5:2.6;if(sp>max){r.vx*=max/sp;r.vy*=max/sp;}if(sp<.7){r.vx*=1.05;r.vy*=1.05;}var nx=r.x+r.vx,ny=r.y+r.vy;if(nx<25||nx>735){r.vx*=-1;nx=Math.max(25,Math.min(735,nx));}if(ny<25||ny>385){r.vy*=-1;ny=Math.max(25,Math.min(385,ny));}for(var j=0;j<this._walls.length;j++){var w=this._walls[j];if(this.circleRect(nx,ny,r.r,w)){if(!this.circleRect(r.x,ny,r.r,w))r.vy*=-1;else if(!this.circleRect(nx,r.y,r.r,w))r.vx*=-1;else{r.vx*=-1;r.vy*=-1;}nx=r.x+r.vx;ny=r.y+r.vy;}}r.x=nx;r.y=ny;r.sprite.x=40+r.x;r.sprite.y=80+r.y;
// RatRun is a 3-frame strip in the first row; alternate frames without changing direction.
var f=(Math.floor(Graphics.frameCount/9)+r.frame)%3;r.sprite.setFrame(f*48,0,48,48);
if(this.inTrap(r)){r.caught=true;r.sprite.opacity=0;this._caught++;this._selected=-1;this._msg('ХЛОП! Крыса поймана — '+this._caught+'/'+this._rats.length);SoundManager.playOk();}}
};
RatCatchScene.prototype.updateSelection=function(){if(this._selected>=0&&!this._rats[this._selected].caught){var r=this._rats[this._selected];r.sprite.opacity=255;}for(var i=0;i<this._rats.length;i++){if(this._rats[i].caught)continue;this._rats[i].sprite.opacity=(i===this._selected?255:210);}};
RatCatchScene.prototype.selectRatAt=function(x,y){var best=-1,bd=42*42;for(var i=0;i<this._rats.length;i++){var r=this._rats[i];if(r.caught)continue;var dx=x-(40+r.x),dy=y-(80+r.y),d=dx*dx+dy*dy;if(d<bd){bd=d;best=i;}}if(best>=0){this._selected=best;this._msg('Крыса выбрана. Теперь нажми ← → ↑ ↓, чтобы махнуть веником.');SoundManager.playCursor();return true;}return false;};
RatCatchScene.prototype.updateControls=function(){var dir=null;if(Input.isTriggered('left')||Input.isTriggered('a'))dir=0;if(Input.isTriggered('right')||Input.isTriggered('d'))dir=1;if(Input.isTriggered('up')||Input.isTriggered('w'))dir=2;if(Input.isTriggered('down')||Input.isTriggered('s'))dir=3;if(TouchInput.isTriggered()){var x=TouchInput.x,y=TouchInput.y;if(this.selectRatAt(x,y))return;for(var i=0;i<this._buttons.length;i++){var b=this._buttons[i];if(x>=b.x&&x<=b.x+145&&y>=b.y&&y<=b.y+62){dir=b._dir;break;}}}if(dir!==null)this.broomHit(dir);};
RatCatchScene.prototype.broomHit=function(dir){if(this._selected<0||!this._rats[this._selected]||this._rats[this._selected].caught){this._msg('Сначала КЛИКНИ ПО КРЫСЕ, чтобы выбрать её!');SoundManager.playBuzzer();return;}if(this._swing>0)return;var r=this._rats[this._selected];var ax=0,ay=0;if(dir===0)ax=-1;if(dir===1)ax=1;if(dir===2)ay=-1;if(dir===3)ay=1;r.vx+=ax*3.2;r.vy+=ay*3.2;r.panic=45;this._hits++;this._swing=16;this._swingDir=dir;this._msg(['ВЗМАХ ВЛЕВО!','ВЗМАХ ВПРАВО!','ВЗМАХ ВВЕРХ!','ВЗМАХ ВНИЗ!'][dir]+' Загоняй её к ловушке!');SoundManager.playCursor();};
RatCatchScene.prototype.updateSwing=function(){if(this._swing<=0)return;this._swing--;var r=this._selected>=0?this._rats[this._selected]:null;if(!r||r.caught)return;var dx=[-1,1,0,0][this._swingDir],dy=[0,0,-1,1][this._swingDir];var p=1-this._swing/16;this._broomX=40+r.x-dx*55*(1-p);this._broomY=80+r.y-dy*55*(1-p);if(!this._broom){this._broom=new Sprite(new Bitmap(150,70));this._broom.anchor.x=.5;this._broom.anchor.y=.5;this.addChild(this._broom);}this._broom.x=this._broomX;this._broom.y=this._broomY;this._broom.opacity=220;this._broom.rotation=Math.atan2(dy,dx);var b=this._broom.bitmap;b.clear();b.fillRect(15,29,80,7,'#9b7650');b.fillRect(86,14,42,38,'#d6b06d');if(this._swing===0)this._broom.opacity=0;};
RatCatchScene.prototype.updateHud=function(){var b=this._stats.bitmap;b.clear();b.font='bold 18px Arial';b.textColor='#f4e1bb';b.drawText('Поймано: '+this._caught+'/'+this._rats.length+'   Взмахов: '+this._hits,0,0,500,'right');b.font='16px Arial';b.textColor='#d6b878';b.drawText('Время: '+Math.ceil(this._time/60)+' сек.',0,25,500,'right');};
RatCatchScene.prototype.inTrap=function(r){var t=this._trap;return r.x>t.x+10&&r.x<t.x+t.w-10&&r.y>t.y+10&&r.y<t.y+t.h-10;};
RatCatchScene.prototype.circleRect=function(cx,cy,r,rect){var px=Math.max(rect.x,Math.min(cx,rect.x+rect.w)),py=Math.max(rect.y,Math.min(cy,rect.y+rect.h)),dx=cx-px,dy=cy-py;return dx*dx+dy*dy<r*r;};
RatCatchScene.prototype.finish=function(win,msg){if(this._ended)return;this._ended=true;this._msg(msg);var ov=new Sprite(new Bitmap(620,180));ov.x=98;ov.y=195;ov.bitmap.fillRect(0,0,620,180,'rgba(25,18,14,.97)');ov.bitmap.font='bold 34px Arial';ov.bitmap.textColor=win?'#9cff9c':'#ff9b8f';ov.bitmap.drawText(win?'ПОДВАЛ ОЧИЩЕН!':'КРЫСЫ РАЗБЕЖАЛИСЬ',0,22,620,45,'center');ov.bitmap.font='19px Arial';ov.bitmap.textColor='#f4e1bb';ov.bitmap.drawText('Поймано: '+this._caught+'/'+this._rats.length+'   Взмахов: '+this._hits,0,82,620,30,'center');ov.bitmap.drawText('Enter / клик — вернуться к квесту',0,125,620,28,'center');this.addChild(ov);if(win){$gameVariables.setValue(11,Number($gameVariables.value(11)||0)+1);if(R.mapId===$gameMap.mapId()&&R.eventId>0)$gameSelfSwitches.setValue([$gameMap.mapId(),R.eventId,'A'],true);}};
window.RatCatchScene=RatCatchScene;
})();
